### PR TITLE
Add some languages

### PR DESCRIPTION
**Pull request by iahung**

### CODE REVIEW

**Comment by ChessMax** [comment]
Thanks!

**Comment by iahung** [comment]
> Thanks!

Please close all of the tickets about BASIC dialects @ChessMax 

I think you should make the final decision to clean the issues page :wink:

**Comment by ChessMax** [comment]
Year, I'm going to replace Basic languages with link to awesome-basic list. Thank you.

**Comment by iahung** [comment]
> Year, I'm going to replace Basic languages with link to awesome-basic list. Thank you.

You don't have to mention that awesome-basic list, just don't add these useless BASICs :wink:

**Pull request merged**
