### PR TITLE
All my A languages

### PR DESCRIPTION
**Pull request by axtens**
A couple have only http URIs. How far back in time may I go? I was going to put http://soft.vub.ac.be/research/agora/ in but it hasn't seen any changes since the late 1990s.

### CODE REVIEW

**Comment by axtens** [comment]
If you prefer, you can just scrape my collection at https://codeaholic-ll.blogspot.com/

**Comment by ChessMax** [comment]
Please fix counters

**Comment by axtens** [comment]
Counters?

**Comment by axtens** [comment]
Oh, *those* counters. Riiight. Ok

**Comment by axtens** [comment]
I'll go ahead and add mine over the next few days. I haven't updated the list since 2006 and there are some dead links in there, along with a tonne of http links that should be updated to https (if they exist)

**Pull request merged**
