### PR TITLE
generated by webapp

### PR DESCRIPTION
**Pull request by axtens**
Generated by calling https://script.google.com/macros/s/AKfycbyI1V4POLmXN8EFrXP-WQ92yH3i08kofD4lC1MV2Ljc1xnE9L4LXoAgt1sbHy8QQIov/exec?readme=1 which reads from a Google Sheets document

### CODE REVIEW

**Comment by axtens** [comment]
What's your opinion regarding esolangs (esoteric languages)? HOPL avoids them as much as possible. They serve various functions but writing useful software in them isn't one of them. They're better for exploration of concepts and as an intellectual challenge for the programmer. Last night I was trawling through https://codeberg.org/catseye looking for languages for this list and disregarded a pile because they were tagged as esolangs. Should I have included them?

**Comment by axtens** [comment]
https://script.google.com/macros/s/AKfycbyI1V4POLmXN8EFrXP-WQ92yH3i08kofD4lC1MV2Ljc1xnE9L4LXoAgt1sbHy8QQIov/exec?languages=S gives all the S languages
https://script.google.com/macros/s/AKfycbyI1V4POLmXN8EFrXP-WQ92yH3i08kofD4lC1MV2Ljc1xnE9L4LXoAgt1sbHy8QQIov/exec?language=kind gives similar detail but just for one language

An HTML fragment is returned rather than a full document

**Comment by ChessMax** [comment]
All colons after counters are removed for some reason

**Comment by axtens** [comment]
Programmer error. Will fix

**Comment by axtens** [comment]
Colon's reinstated. Webapp removed. Still have lots of languages to add if that's still okay with you.

**Pull request merged**
